---
- name: Ensure dockprom folder exists
  file:
    path: "{{ dockprom_path }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Pull and start Dockprom stack
  community.docker.docker_compose:
    project_src: "{{ dockprom_path }}"
    state: present
    restarted: true
