---
- name: Ensure default users exist
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups | default(omit) }}"
    state: present
    create_home: true
  loop: "{{ default_users }}"

- name: Ensure SSH keys are present
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.ssh_key }}"
    state: present
  loop: "{{ default_users }}"
