---
common_packages_debian:
  - sudo
  - curl
  - wget
  - vim
  - git
  - unzip
  - tar
  - bash-completion
  - net-tools
  - htop
  - lsof
  - iproute2
  - traceroute
  - dnsutils
  - netcat
  - jq
  - ca-certificates
  - python3
  - python3-venv

common_packages_redhat:
  - sudo
  - curl
  - wget
  - vim
  - git
  - unzip
  - tar
  - bash-completion
  - net-tools
  - htop
  - lsof
  - iproute
  - traceroute
  - bind-utils
  - nc
  - jq
  - ca-certificates
  - python3
  - python3-venv
