plugin: netbox.netbox.nb_inventory
api_endpoint: {{ NETBOX_API }}
token: {{ NETBOX_API_TOKEN }}
validate_certs: false
config_context: true
query_filters:
  - status: active
  - tag: ansible
group_by:
  - device_roles
  - sites
compose:
  ansible_host: "{{ primary_ip4.address | default('') | regex_replace('/.*$','') }}"
  ansible_user: "{{ custom_fields.ansible_user | default('ansible') }}"