---
- name: Configure UFW on Debian-based OS
  ufw:
    state: enabled
    rule: allow
    name: OpenSSH
  when: ansible_os_family == "Debian"

- name: Set default deny policies on Debian
  ufw:
    state: enabled
    policy: deny
  when: ansible_os_family == "Debian"

- name: Configure firewalld on RedHat-based OS
  firewalld:
    service: ssh
    permanent: yes
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"

- name: Set default deny policy RedHat
  firewalld:
    state: enabled
    immediate: yes
  when: ansible_os_family == "RedHat"
